content = open('dashboard/src/App.jsx', 'r', encoding='utf-8').read()
lines = content.split('\n')

# Find renderSmartSimulatorTab start and end (0-indexed)
start = None
end = None
for i, l in enumerate(lines):
    if 'const renderSmartSimulatorTab' in l and start is None:
        start = i
    if start and i > start and (l.strip().startswith('// ---') or (l.strip() == '};' and i > start + 5)):
        end = i + 1
        break
if not end:
    end = len(lines)

print(f'renderSmartSimulatorTab: lines {start+1} to {end}')

new_fn = [
  "  // ------------ TAB 5: AI SMART FARM SIMULATOR (XGBOOST) ------------",
  "  const renderSmartSimulatorTab = () => {",
  "    return (",
  "      <div style={{ animation: 'fade-in 0.8s' }}>",
  "        <div style={{ marginBottom: '2rem' }}>",
  "          <h2 style={{color: 'white', fontSize: '2rem', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '15px'}}>",
  "            <Cpu size={36} color=\"var(--text-highlight)\"/> AI Smart Farm Simulator",
  "          </h2>",
  "          <p style={{color: 'var(--text-main)'}}>Dual XGBoost engine: Disease Risk + Milk Yield Intelligence in one unified inference pass.</p>",
  "        </div>",
  "",
  "        <div style={{ display: 'grid', gridTemplateColumns: '360px 1fr', gap: '2rem' }}>",
  "          {/* CONTROL PANEL */}",
  "          <div className=\"glass-panel\" style={{ padding: '1.5rem', height: 'fit-content' }}>",
  "            <h3 style={{color: 'var(--text-highlight)', marginBottom: '1.5rem', fontSize: '1rem', letterSpacing: '1px'}}>FARM CONTROL KNOBS</h3>",
  "            <div style={{ display: 'flex', flexDirection: 'column', gap: '1.2rem' }}>",
  "",
  "              <div style={{ fontSize: '0.75rem', color: 'var(--text-highlight)', fontWeight: 'bold', letterSpacing: '2px' }}>BIOLOGICAL VITALS</div>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem' }}>",
  "                <div>",
  "                  <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Body Temp (C)</label>",
  "                  <input type=\"number\" step=\"0.1\" value={smartInputs.body_temp}",
  "                    onChange={(e) => setSmartInputs({...smartInputs, body_temp: parseFloat(e.target.value)})}",
  "                    style={{width: '100%', padding: '7px', borderRadius: '4px', background: 'rgba(0,0,0,0.4)', color: 'white', border: '1px solid rgba(255,255,255,0.15)', boxSizing: 'border-box'}} />",
  "                </div>",
  "                <div>",
  "                  <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Heart Rate (BPM)</label>",
  "                  <input type=\"number\" value={smartInputs.heart_rate}",
  "                    onChange={(e) => setSmartInputs({...smartInputs, heart_rate: parseInt(e.target.value)})}",
  "                    style={{width: '100%', padding: '7px', borderRadius: '4px', background: 'rgba(0,0,0,0.4)', color: 'white', border: '1px solid rgba(255,255,255,0.15)', boxSizing: 'border-box'}} />",
  "                </div>",
  "                <div>",
  "                  <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Resp. Rate (/min)</label>",
  "                  <input type=\"number\" value={smartInputs.resp_rate}",
  "                    onChange={(e) => setSmartInputs({...smartInputs, resp_rate: parseInt(e.target.value)})}",
  "                    style={{width: '100%', padding: '7px', borderRadius: '4px', background: 'rgba(0,0,0,0.4)', color: 'white', border: '1px solid rgba(255,255,255,0.15)', boxSizing: 'border-box'}} />",
  "                </div>",
  "              </div>",
  "",
  "              <div style={{ fontSize: '0.75rem', color: 'var(--text-highlight)', fontWeight: 'bold', letterSpacing: '2px' }}>ENVIRONMENT</div>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem' }}>",
  "                <div>",
  "                  <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Ambient Temp (C)</label>",
  "                  <input type=\"number\" value={smartInputs.ambient_temp}",
  "                    onChange={(e) => setSmartInputs({...smartInputs, ambient_temp: parseFloat(e.target.value)})}",
  "                    style={{width: '100%', padding: '7px', borderRadius: '4px', background: 'rgba(0,0,0,0.4)', color: 'white', border: '1px solid rgba(255,255,255,0.15)', boxSizing: 'border-box'}} />",
  "                </div>",
  "                <div>",
  "                  <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Humidity (%)</label>",
  "                  <input type=\"number\" value={smartInputs.humidity}",
  "                    onChange={(e) => setSmartInputs({...smartInputs, humidity: parseFloat(e.target.value)})}",
  "                    style={{width: '100%', padding: '7px', borderRadius: '4px', background: 'rgba(0,0,0,0.4)', color: 'white', border: '1px solid rgba(255,255,255,0.15)', boxSizing: 'border-box'}} />",
  "                </div>",
  "              </div>",
  "",
  "              <div style={{ fontSize: '0.75rem', color: 'var(--text-highlight)', fontWeight: 'bold', letterSpacing: '2px' }}>NUTRITION + LACTATION</div>",
  "              <div>",
  "                <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Feed Quantity: {smartInputs.feed_qty} kg</label>",
  "                <input type=\"range\" min=\"5\" max=\"30\" step=\"0.5\" value={smartInputs.feed_qty}",
  "                  onChange={(e) => setSmartInputs({...smartInputs, feed_qty: parseFloat(e.target.value)})}",
  "                  style={{width: '100%', accentColor: 'var(--text-highlight)'}} />",
  "              </div>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem' }}>",
  "                <div>",
  "                  <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Feeding Freq/day</label>",
  "                  <input type=\"number\" min=\"1\" max=\"6\" value={smartInputs.feeding_frequency}",
  "                    onChange={(e) => setSmartInputs({...smartInputs, feeding_frequency: parseInt(e.target.value)})}",
  "                    style={{width: '100%', padding: '7px', borderRadius: '4px', background: 'rgba(0,0,0,0.4)', color: 'white', border: '1px solid rgba(255,255,255,0.15)', boxSizing: 'border-box'}} />",
  "                </div>",
  "                <div>",
  "                  <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Days in Milk</label>",
  "                  <input type=\"number\" value={smartInputs.days_in_milk}",
  "                    onChange={(e) => setSmartInputs({...smartInputs, days_in_milk: parseInt(e.target.value)})}",
  "                    style={{width: '100%', padding: '7px', borderRadius: '4px', background: 'rgba(0,0,0,0.4)', color: 'white', border: '1px solid rgba(255,255,255,0.15)', boxSizing: 'border-box'}} />",
  "                </div>",
  "                <div>",
  "                  <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Prev Week Avg (L)</label>",
  "                  <input type=\"number\" step=\"0.1\" value={smartInputs.prev_week_avg}",
  "                    onChange={(e) => setSmartInputs({...smartInputs, prev_week_avg: parseFloat(e.target.value)})}",
  "                    style={{width: '100%', padding: '7px', borderRadius: '4px', background: 'rgba(0,0,0,0.4)', color: 'white', border: '1px solid rgba(255,255,255,0.15)', boxSizing: 'border-box'}} />",
  "                </div>",
  "                <div>",
  "                  <label style={{color: 'var(--text-main)', display: 'block', marginBottom: '4px', fontSize: '0.75rem'}}>Actual Yield Today (L)</label>",
  "                  <input type=\"number\" step=\"0.1\" value={smartInputs.actual_yield}",
  "                    onChange={(e) => setSmartInputs({...smartInputs, actual_yield: parseFloat(e.target.value)})}",
  "                    style={{width: '100%', padding: '7px', borderRadius: '4px', background: 'rgba(0,0,0,0.4)', color: 'white', border: '1px solid rgba(255,255,255,0.15)', boxSizing: 'border-box'}} />",
  "                </div>",
  "              </div>",
  "",
  "              <button onClick={handleSmartInference} disabled={isInferringSmart}",
  "                style={{ padding: '14px', borderRadius: '8px', border: 'none',",
  "                  background: isInferringSmart ? 'rgba(100,255,218,0.3)' : 'var(--text-highlight)',",
  "                  color: 'black', fontWeight: 'bold', fontSize: '1rem',",
  "                  cursor: isInferringSmart ? 'not-allowed' : 'pointer',",
  "                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>",
  "                {isInferringSmart ? 'Running XGBoost...' : <><Zap size={18}/> Run Dual AI Inference</>}",
  "              </button>",
  "            </div>",
  "          </div>",
  "",
  "          {/* OUTPUT PANEL */}",
  "          <div>",
  "            {!smartResult && !isInferringSmart && (",
  "              <div style={{ height: '450px', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', border: '2px dashed rgba(255,255,255,0.08)', borderRadius: '16px' }}>",
  "                <BrainCircuit size={70} style={{opacity: 0.15, marginBottom: '16px'}}/>",
  "                <p style={{color: 'var(--text-main)', fontSize: '1.1rem'}}>Set your farm parameters and run the AI diagnostic.</p>",
  "                <p style={{color: 'var(--text-main)', fontSize: '0.85rem', marginTop: '6px'}}>Both Disease + Yield models will run simultaneously.</p>",
  "              </div>",
  "            )}",
  "            {isInferringSmart && (",
  "              <div style={{ height: '450px', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>",
  "                <div style={{ width: '48px', height: '48px', border: '4px solid rgba(100,255,218,0.1)', borderTopColor: 'var(--text-highlight)', borderRadius: '50%', animation: 'spin 0.8s linear infinite' }}></div>",
  "                <p style={{color: 'var(--text-highlight)', marginTop: '18px', fontSize: '1rem'}}>Running Dual XGBoost Inference...</p>",
  "              </div>",
  "            )}",
  "            {smartResult && (",
  "              <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>",
  "",
  "                {/* ROW 1: Disease + Yield side by side */}",
  "                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>",
  "",
  "                  {/* DISEASE CARD */}",
  "                  <div className=\"glass-panel\" style={{ padding: '1.5rem', borderTop: smartResult.health.risk_pct > 50 ? '4px solid var(--danger)' : smartResult.health.risk_pct > 30 ? '4px solid #FF9800' : '4px solid #4CAF50' }}>",
  "                    <h3 style={{color: 'white', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '1rem'}}><HeartPulse size={20}/> Disease Risk Model</h3>",
  "                    <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem', marginBottom: '1.2rem' }}>",
  "                      <div style={{ width: '100px', height: '100px', flexShrink: 0 }}>",
  "                        <ResponsiveContainer width=\"100%\" height=\"100%\">",
  "                          <RadialBarChart cx=\"50%\" cy=\"50%\" innerRadius=\"65%\" outerRadius=\"100%\" barSize={10}",
  "                            data={[{ name: 'Risk', value: smartResult.health.risk_pct, fill: smartResult.health.risk_pct > 50 ? 'var(--danger)' : smartResult.health.risk_pct > 30 ? '#FF9800' : '#4CAF50' }]}",
  "                            startAngle={180} endAngle={0}>",
  "                            <RadialBar background dataKey=\"value\" cornerRadius={8} />",
  "                            <text x=\"50%\" y=\"42%\" textAnchor=\"middle\" dominantBaseline=\"middle\" style={{ fill: 'white', fontSize: '1rem', fontWeight: 'bold' }}>",
  "                              {smartResult.health.risk_pct}%",
  "                            </text>",
  "                          </RadialBarChart>",
  "                        </ResponsiveContainer>",
  "                      </div>",
  "                      <div>",
  "                        <div style={{ fontSize: '1.3rem', fontWeight: 'bold', color: smartResult.health.risk_pct > 50 ? 'var(--danger)' : smartResult.health.risk_pct > 30 ? '#FF9800' : '#4CAF50' }}>{smartResult.health.status}</div>",
  "                        <div style={{ color: 'var(--text-main)', fontSize: '0.8rem', marginTop: '4px' }}>XGBoost Disease Probability</div>",
  "                      </div>",
  "                    </div>",
  "                    {smartResult.health.warnings.length > 0 && (",
  "                      <div style={{ marginBottom: '1rem' }}>",
  "                        {smartResult.health.warnings.map((w, i) => (",
  "                          <div key={i} style={{ padding: '6px 10px', background: 'rgba(255,82,82,0.1)', borderLeft: '3px solid var(--danger)', borderRadius: '4px', color: '#ffb3b3', fontSize: '0.8rem', marginBottom: '5px' }}>",
  "                            {w}",
  "                          </div>",
  "                        ))}",
  "                      </div>",
  "                    )}",
  "                    <div style={{ background: 'rgba(255,255,255,0.04)', padding: '1rem', borderRadius: '8px', fontSize: '0.85rem', color: 'white', lineHeight: '1.5' }}>",
  "                      {smartResult.health.decision}",
  "                    </div>",
  "                  </div>",
  "",
  "                  {/* YIELD CARD */}",
  "                  <div className=\"glass-panel\" style={{ padding: '1.5rem', borderTop: '4px solid var(--text-highlight)' }}>",
  "                    <h3 style={{color: 'white', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '1rem'}}><BarChart3 size={20}/> Milk Yield Model</h3>",
  "                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem', marginBottom: '1rem' }}>",
  "                      <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.9rem', borderRadius: '8px', textAlign: 'center' }}>",
  "                        <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginBottom: '4px' }}>Predicted Yield</div>",
  "                        <div style={{ color: 'var(--text-highlight)', fontSize: '1.6rem', fontWeight: 'bold' }}>{smartResult.production.predicted_yield}L</div>",
  "                      </div>",
  "                      <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.9rem', borderRadius: '8px', textAlign: 'center' }}>",
  "                        <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginBottom: '4px' }}>Performance Score</div>",
  "                        <div style={{ color: '#ffeb3b', fontSize: '1.6rem', fontWeight: 'bold' }}>{smartResult.production.performance_score}/100</div>",
  "                      </div>",
  "                    </div>",
  "                    <div style={{ background: 'rgba(255,255,255,0.04)', padding: '0.9rem', borderRadius: '8px', textAlign: 'center', marginBottom: '0.8rem' }}>",
  "                      <div style={{ color: 'var(--text-main)', fontSize: '0.75rem' }}>Cow Performance Label</div>",
  "                      <div style={{ color: '#ffeb3b', fontWeight: 'bold', fontSize: '1rem', marginTop: '4px' }}>{smartResult.production.performance_label}</div>",
  "                    </div>",
  "                    {smartResult.production.yield_alert && (",
  "                      <div style={{ padding: '10px', background: 'rgba(255,82,82,0.12)', border: '1px solid rgba(255,82,82,0.4)', borderRadius: '6px', color: '#ffb3b3', fontSize: '0.8rem' }}>",
  "                        {smartResult.production.yield_alert}",
  "                      </div>",
  "                    )}",
  "                  </div>",
  "                </div>",
  "",
  "                {/* ROW 2: 7 Intelligence Metrics */}",
  "                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem' }}>",
  "                  <div className=\"glass-panel\" style={{ padding: '1.2rem', borderLeft: '3px solid #4CAF50' }}>",
  "                    <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginBottom: '4px' }}>Feed +2kg Gain</div>",
  "                    <div style={{ color: '#4CAF50', fontSize: '1.4rem', fontWeight: 'bold' }}>+{smartResult.production.feed_gain}L</div>",
  "                    <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginTop: '4px' }}>per day yield boost</div>",
  "                  </div>",
  "                  <div className=\"glass-panel\" style={{ padding: '1.2rem', borderLeft: '3px solid var(--danger)' }}>",
  "                    <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginBottom: '4px' }}>Heat Stress Loss</div>",
  "                    <div style={{ color: 'var(--danger)', fontSize: '1.4rem', fontWeight: 'bold' }}>-{smartResult.production.climate_penalty}L</div>",
  "                    <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginTop: '4px' }}>vs ideal 22C/50%RH</div>",
  "                  </div>",
  "                  <div className=\"glass-panel\" style={{ padding: '1.2rem', borderLeft: `3px solid ${smartResult.production.trend_delta >= 0 ? '#4CAF50' : 'var(--danger)'}` }}>",
  "                    <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginBottom: '4px' }}>7-Day Yield Trend</div>",
  "                    <div style={{ color: smartResult.production.trend_delta >= 0 ? '#4CAF50' : 'var(--danger)', fontSize: '1.4rem', fontWeight: 'bold' }}>",
  "                      {smartResult.production.trend_delta >= 0 ? '+' : ''}{smartResult.production.trend_delta}L",
  "                    </div>",
  "                    <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginTop: '4px' }}>Next week: {smartResult.production.future_yield_7d}L</div>",
  "                  </div>",
  "                  <div className=\"glass-panel\" style={{ padding: '1.2rem', borderLeft: '3px solid var(--text-highlight)' }}>",
  "                    <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginBottom: '4px' }}>What-If: Feed +5kg</div>",
  "                    <div style={{ color: 'var(--text-highlight)', fontSize: '1.4rem', fontWeight: 'bold' }}>{smartResult.production.whatif_yield_plus5kg}L</div>",
  "                    <div style={{ color: 'var(--text-main)', fontSize: '0.7rem', marginTop: '4px' }}>max scenario yield</div>",
  "                  </div>",
  "                </div>",
  "",
  "                {/* ROW 3: Yield bar chart */}",
  "                <div className=\"glass-panel\" style={{ padding: '1.5rem' }}>",
  "                  <h3 style={{ color: 'white', marginBottom: '1rem', fontSize: '0.95rem' }}>Yield Scenario Comparison</h3>",
  "                  <ResponsiveContainer width=\"100%\" height={200}>",
  "                    <BarChart data={[",
  "                      { name: 'Actual', value: smartInputs.actual_yield, fill: '#9E9E9E' },",
  "                      { name: 'AI Predicted', value: smartResult.production.predicted_yield, fill: 'var(--text-highlight)' },",
  "                      { name: 'Feed Optimized', value: smartResult.production.optimized_yield, fill: '#4CAF50' },",
  "                      { name: 'What-If +5kg', value: smartResult.production.whatif_yield_plus5kg, fill: '#2196F3' },",
  "                      { name: 'Ideal Climate', value: parseFloat((smartResult.production.predicted_yield + smartResult.production.climate_penalty).toFixed(2)), fill: '#FF9800' },",
  "                    ]} margin={{ top: 5, right: 20, left: 0, bottom: 5 }}>",
  "                      <CartesianGrid strokeDasharray=\"3 3\" stroke=\"rgba(255,255,255,0.05)\" vertical={false} />",
  "                      <XAxis dataKey=\"name\" stroke=\"var(--text-main)\" tick={{ fontSize: 11 }} />",
  "                      <YAxis stroke=\"var(--text-main)\" domain={['auto', 'auto']} tick={{ fontSize: 11 }} />",
  "                      <Tooltip contentStyle={{ backgroundColor: '#1a1a2e', borderColor: 'var(--text-highlight)', color: '#fff' }} formatter={(v) => [v + ' L', 'Yield']} />",
  "                      <Bar dataKey=\"value\" radius={[4,4,0,0]}>",
  "                        {[",
  "                          { fill: '#9E9E9E' },",
  "                          { fill: 'var(--text-highlight)' },",
  "                          { fill: '#4CAF50' },",
  "                          { fill: '#2196F3' },",
  "                          { fill: '#FF9800' },",
  "                        ].map((c, i) => <Cell key={i} fill={c.fill} />)}",
  "                      </Bar>",
  "                    </BarChart>",
  "                  </ResponsiveContainer>",
  "                </div>",
  "",
  "              </div>",
  "            )}",
  "          </div>",
  "        </div>",
  "      </div>",
  "    );",
  "  };",
  "",
]

new_lines = lines[:start] + new_fn + lines[end:]
open('dashboard/src/App.jsx', 'w', encoding='utf-8').write('\n'.join(new_lines))
print('Done. Lines:', len(new_lines))
